name: Update Reddit Stats

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install dependencies and run script
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip wget
        sudo pip3 install requests pyaml
        python3 scripts/reddit-stats.py
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add _data/*
        git commit -a -m "Automated deployment to update Reddit Stats $(date '+%Y-%m-%d')" --allow-empty
        git push origin main
